version: "3.8"
services:
  trafficlaw_chatbot_container:
    container_name: trafficlaw_chatbot_container
    image: pgvector/pgvector:0.8.1-pg17-trixie
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trafficlawdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpass
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/17/bin
      - GOSU_VERSION=1.17
      - LANG=en_US.utf8
      - PG_MAJOR=17
      - PG_VERSION=17.6-1.pgdg13+1
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
    restart: "no"

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge
